export const actionTypes = {
  GET_SEASONS_LOADING: "LOAD_SEASONS_LOADING",
  GET_SEASONS_FAIL: "LOAD_SEASONS_FAIL",
  GET_SEASONS_OK: "LOAD_SEASONS_OK",
  GET_SEASONS_DATA: "LOAD_SEASONS_DATA",
  GET_PLAYS_LOADING: "GET_PLAYS_LOADING",
  GET_PLAYS_FAIL: "GET_PLAYS_FAIL",
  GET_PLAYS_OK: "GET_PLAYS_OK",
  CREATE_NEW_PLAY: "CREATE_NEW_PLAY",
};
